apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: keladay-wind-turbine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: keladay-wind-turbine
    app.kubernetes.io/part-of: keladay-wind-turbine
  name: keladay-wind-turbine
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: keladay-wind-turbine
status:
  loadBalancer: {}
